version: "3"
services:
  app:
    image: flask-app:v1
    ports: 
      - "5000:5000"
    environment:
       MYSQL_HOST: "mysql"
       MYSQL_USER: "admin"
       MYSQL_PASSWORD: "admin" 
       MYSQL_DB: "myDB"
    depends_on:
      -  mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
       MYSQL_DATABASE: myDB
       MYSQL_USER: "admin"
       MYSQL_PASSWORD: "admin"
       MYSQL_ROOT_PASSWORD: "admin" 
